### ISSUE TITLE
KeyError: 'verbosity'

### ISSUE THREAD

**Issue by ljljlj02** [jackyko1991/vnet-tensorflow#17]
when i run train.py ,something went wrong:KeyError: 'verbosity'

2020-06-14 16:28:44.548595: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "D:/vnet-tensorflow-master/train.py", line 625, in <module>
    tf.compat.v1.app.run()
  File "E:\Ana\envs\py374\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "E:\Ana\envs\py374\lib\site-packages\absl\app.py", line 293, in run
    flags_parser,
  File "E:\Ana\envs\py374\lib\site-packages\absl\app.py", line 359, in _run_init
    logging.use_absl_handler()
  File "E:\Ana\envs\py374\lib\site-packages\absl\logging\__init__.py", line 1148, in use_absl_handler
    FLAGS['verbosity']._update_logging_levels()  # pylint: disable=protected-access
  File "E:\Ana\envs\py374\lib\site-packages\absl\flags\_flagvalues.py", line 463, in __getitem__
    return self._flags()[name]
KeyError: 'verbosity'

How can I solve this problem? (my python version is 3.7.4,tensorflow-gpu==1.14.0,Anaconda nvironment is ok. )

**Comment by jackyko1991** [comment]
I wonder if you are training with Windows environment. The code is only tested on Ubuntu 18.04. 

The error shows that absl logging environment maybe inconsistent for Windows and Linux Tensorflow built.

**Comment by ljljlj02** [comment]
I did run it on Windows 10.

**Comment by zhangkun0220** [comment]
I encountered the same situation as you. Have you finally solved it？

**Comment by ljljlj02** [comment]
No, I have now given up using TensorFlow, Pytorch (or MONAI) may be a better option.

**Comment by ljljlj02** [comment]
> I encountered the same situation as you. Have you finally solved it？

No, I have now given up using TensorFlow, Pytorch (or MONAI) may be a better option.

**Comment by zhangkun0220** [comment]
well, thanks












张昆
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, Mar 10, 2022 08:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jackyko1991/vnet-tensorflow] KeyError: 'verbosity' (#17)




 
No, I have now given up using TensorFlow, Pytorch (or MONAI) may be a better option.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AnishTatke** [comment]
Facing the same issue on Ubuntu system connected remotely via Windows 10 machine. Has anyone figured out a way to resolve this error?
